MODEL:
  BASE: "models/detections/det_yolov4x_cspdarknet.yaml"
  BBOX_HEAD:
    num_classes: 116
DATA:
  BASE: "datasets/detections/det_retail_mosaic.yaml"
  ROOT_PATH: "/Users/qianzhiming/Desktop/data/objdet-datasets/RetailDet"
  TRAIN_DATA:
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 0
  VAL_DATA:
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 0
  TEST_DATA:
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 0
SCHEDULE:
  BASE: "schedulers/schedule_yolo.yaml"
  TOTAL_EPOCHS: 300
  OPTIMIZER:
    lr: 0.001
RUNTIME:
  BASE: "runtimes/runtime_yolo.yaml"
