MODEL:
  BASE: "models/detections/det_yolov5.yaml"
  BACKBONE:
    depth_multiple: 0.33  # {s:0.33, m: 0.67, l: 1.0, x: 1.33}
    width_multiple: 0.5  # {s:0.5, m: 0.75, l: 1.0, x: 1.25}  
  BBOX_HEAD:
    num_classes: 2
    dw_ratios: [0.33, 0.5]
DATA:
  BASE: "datasets/detections/det_catdoghead_yolo.yaml"
  ROOT_PATH: "/Users/qianzhiming/Desktop/data/objdet-datasets/CatDogHeadDet"
  TRAIN_DATA:
    DATA_INFO: [['tfrecords/train.tfrecord']] # ["metas/train.txt"]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    DATA_INFO: [['tfrecords/val.tfrecord']] # ["metas/val.txt"]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    DATA_INFO: [['tfrecords/val.tfrecord']] # ["metas/val.txt"]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
SCHEDULE:
  BASE: "schedulers/schedule_yolo.yaml"
  TOTAL_EPOCHS: 100
  OPTIMIZER:
    lr: 0.001
  LR_POLICY:
    warmup_iters: 5000
    warmup_ratio: 0.001
    step: [66, 92]
RUNTIME:
  BASE: "runtimes/local_runtime.yaml"
