MODEL:
  BASE: "models/detections/det_faster_rcnn_r50_fpn.yaml"
  ROI_HEAD:
    bbox_head:
      num_classes: 20
DATA:
  BASE: "datasets/detections/det_voc.yaml"
SCHEDULE:
  BASE: "schedulers/schedule_2x.yaml"
  OPTIMIZER: 
    lr: 0.002
RUNTIME:
  BASE: "runtimes/local_runtime.yaml"
