MODEL:
  BASE: "models/detections/det_yolov4_cspdarknet.yaml"
  PRETRAINED_MODEL_PATH: ""
  BBOX_HEAD:
    num_classes: 1
    anchor_generator: {
      type: 'YOLOAnchorGenerator',
      base_sizes: [[[75, 100], [54, 67]],
                    [[48, 32], [41, 56]],
                    [[35, 45], [27, 38]]],
      strides: [32, 16, 8]}

  TEST_CFG:
    nms_pre: 1000
    min_bbox_size: 0
    score_thr: 0.05
    conf_thr: 0.005
    nms: {
      type: 'common_nms', 
      iou_threshold: 0.75 }
    max_per_img: 100
DATA:
  BASE: "datasets/detections/det_retail_one_yolo.yaml"
  ROOT_PATH: "data/"
  TRAIN_DATA:
    DATA_INFO: ["train/a_train_annotations.json"]
    SAMPLES_PER_DEVICE: 2
    WORKERS_PER_DEVICE: 2
  VAL_DATA:
    DATA_PREFIX: ["train/a_images/"] 
    DATA_INFO: ["train/a_val_annotations.json"]
    SAMPLES_PER_DEVICE: 2
    WORKERS_PER_DEVICE: 2
  TEST_DATA:
    DATA_PREFIX: ["train/a_images/"] 
    DATA_INFO: ["train/a_val_annotations.json"]
    SAMPLES_PER_DEVICE: 2
    WORKERS_PER_DEVICE: 2
SCHEDULE:
  BASE: "schedulers/schedule_yolo.yaml"
  TOTAL_EPOCHS: 200
  OPTIMIZER:
    lr: 0.001
  LR_POLICY:
    policy: "CosineAnnealing"
    min_lr_ratio: 0.2
RUNTIME:
  BASE: "runtimes/local_runtime.yaml"
  CHECKPOINT_CONFIG:
    interval: 2
  LOG_CONFIG:
    interval: 20
    hooks: {
      TextLoggerHook: {ignore_last: False},
      TensorboardLoggerHook: {}
    }
