MODEL:
  BASE: "models/detections/det_ssd_300_vgg.yaml"
  PRETRAINED_MODEL_PATH: "meta/models/vgg16_caffe-292e1171.pth"
  BBOX_HEAD:
    num_classes: 116
DATA:
  BASE: "datasets/detections/det_retail.yaml"
  ROOT_PATH: "/Users/qianzhiming/Desktop/data/objdet-datasets/RetailDet"
  TRAIN_DATA:
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
SCHEDULE:
  BASE: "schedulers/schedule_efficient.yaml"
  OPTIMIZER: 
    lr: 0.0001
RUNTIME:
  BASE: "runtimes/local_runtime.yaml"
