MODEL:
  BASE: "models/detections/det_yolov4s_cspdarknet.yaml"
  BBOX_HEAD:
    num_classes: 116
DATA:
  BASE: "datasets/detections/det_retail_yolo.yaml"
  ROOT_PATH: "data"
  TRAIN_TRANSFORMS:
    JointResize: {
      img_scale: [[416, 416]],
      keep_ratio: True}
  TRAIN_DATA:
    TYPE: "Normal" # "Normal" "Concat" "Repeat" "Balanced"
    FLAG: 1
    DATA_INFO: ["train/a_annotations.json"]
    DATA_PREFIX: ["train/a_images/"]
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: ["train/a_annotations.json"]
    DATA_PREFIX: ["train/a_images/"]
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: ["test/a_annotations.json"]
    DATA_PREFIX: ["test/a_images"]
    TEST_MODE: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
SCHEDULE:
  BASE: "schedulers/schedule_yolo.yaml"
  TOTAL_EPOCHS: 300
  OPTIMIZER:
    lr: 0.001
RUNTIME:
  BASE: "runtimes/runtime_yolo.yaml"
