MODEL:
  BASE: "models/detections/det_efficientdet_d7.yaml"
  BBOX_HEAD:
    num_classes: 116
DATA:
  BASE: "datasets/detections/det_retail_mosaic.yaml"
  ROOT_PATH: "/Users/qianzhiming/Desktop/data/objdet-datasets/RetailDet"
  TRAIN_TRANSFORMS:
    MosaicPipeline: {
      individual_pipeline: {
        LoadImageFromFile: {backend: 'turbojpeg'},
        LoadAnnotations: {with_bbox: True},
        JointResize: {img_scale: [608, 608], keep_ratio: True}
      }, pad_val: 114}
    Albu: {
      update_pad_shape: True,
      skip_img_without_anno: False,
      bbox_params: {
        type: 'BboxParams',
        format: 'pascal_voc',
        min_area: 4,
        min_visibility: 0.2,
        label_fields: ['gt_labels'],
        check_each_transform: False},
      transforms: {
        PadIfNeeded: {
          min_height: 1824,
          min_width: 1824,
          border_mode: 0,
          value: [114, 114, 114],
          always_apply: True},
        RandomCrop: {
          width: 1216,
          height: 1216,
          always_apply: True},
        RandomScale: {
          scale_limit: 0.5,
          interpolation: 1,
          always_apply: True},
        CenterCrop: {
          width: 608,
          height: 608,
          always_apply: True},
        HorizontalFlip: {p: 0.5}}}    
  TEST_TRANSFORMS:  
    MultiScaleFlipAug: {
      img_scale: [608, 608],
      flip: False,
      transforms: {
        JointResize: {keep_ratio: True},
        RandomFlip: {},
        Pad: {size_divisor: 32},
        Normalize: {
          mean: [114, 114, 114],
          std: [255, 255, 255],
          to_rgb: True},
        ImageToTensor: {keys: ['img']},
        Collect: {keys: ['img']}
        }
      }
  TRAIN_DATA:
    DATA_INFO: [['tfrecords/train.tfrecord']] # ["metas/train.txt"]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    DATA_INFO: [['tfrecords/val.tfrecord']] # ["metas/val.txt"]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    DATA_INFO: [['tfrecords/val.tfrecord']] # ["metas/val.txt"]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
SCHEDULE:
  BASE: "schedulers/schedule_efficient.yaml"
  TOTAL_EPOCHS: 200
  OPTIMIZER:
    lr: 0.01
  LR_POLICY:
    warmup_iters: 2000
    warmup_ratio: 0.008
RUNTIME:
  BASE: "runtimes/local_runtime.yaml"
