MODEL:
  BASE: "models/detections/det_yolov3_darknet.yaml"
  PRETRAINED_MODEL_PATH: ""
  BBOX_HEAD:
    num_classes: 20
DATA:
  BASE: "datasets/detections/det_voc_yolo.yaml"
  ROOT_PATH: "/home/qzm/Work/Data/VOC/VOCdevkit"
  TRAIN_DATA:
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
SCHEDULE:
  BASE: "schedulers/schedule_yolo.yaml"
  OPTIMIZER: 
    lr: 0.001
RUNTIME:
  BASE: "runtimes/local_runtime.yaml"
  LOG_CONFIG:
    interval: 10
