MODEL:
  BASE: "models/detections/det_faster_rcnn_r50_fpn.yaml"
  ROI_HEAD:
    bbox_head:
      num_classes: 65
DATA:
  BASE: "datasets/detections/det_multiobj.yaml"
  TRAIN_DATA:
    DATA_INFO: [['tfrecords/train_01.tfrecord', 'tfrecords/train_02.tfrecord', 'tfrecords/train_03.tfrecord',
                 'tfrecords/train_04.tfrecord', 'tfrecords/train_05.tfrecord', 'tfrecords/train_06.tfrecord',
                 'tfrecords/train_07.tfrecord', 'tfrecords/train_08.tfrecord', 'tfrecords/train_09.tfrecord']] # ["metas/train.txt"]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    DATA_INFO: [['tfrecords/val.tfrecord']] # ["metas/val.txt"]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    DATA_INFO: [['tfrecords/val.tfrecord']] # ["metas/val.txt"]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
SCHEDULE:
  BASE: "schedulers/schedule_2x.yaml"
  OPTIMIZER: 
    lr: 0.01
RUNTIME:
  BASE: "runtimes/local_runtime.yaml"
