MODEL:
  BASE: "models/detections/det_faster_rcnn_r50_fpn.yaml"
  ROI_HEAD:
    bbox_head:
      num_classes: 2
DATA:
  BASE: "datasets/detections/det_catdog_head.yaml"
  # ROOT_PATH: "/apdcephfs/share_1326378/public_data/cv/det/CatDogHeadDet"
  TRAIN_DATA:
    DATA_INFO: [['tfrecords/train.tfrecord']] # ["metas/train.txt"]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    DATA_INFO: [['tfrecords/val.tfrecord']] # ["metas/val.txt"]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    DATA_INFO: [['tfrecords/val.tfrecord']] # ["metas/val.txt"]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
SCHEDULE:
  BASE: "schedulers/schedule_2x.yaml"
  TOTAL_EPOCHS: 100
  OPTIMIZER:
    lr: 0.01
  LR_POLICY:
    step: [60, 80]
RUNTIME:
  BASE: "runtimes/local_runtime.yaml"
