MODEL:
  BASE: "models/detections/det_ssd_300_vgg.yaml"
DATA:
  BASE: "datasets/detections/det_mosaic.yaml"
SCHEDULE:
  BASE: "schedulers/schedule_2x.yaml"
  OPTIMIZER: 
    lr: 0.001
RUNTIME:
  BASE: "runtimes/local_runtime.yaml"
