DATA:
  NAME: "CocoDataset"
  ROOT_PATH: "data/objdet-datasets/COCO"
  TRAIN_TRANSFORMS:
    LoadImageFromFile: {
      to_float32: True,
      backend: 'pillow',
      channel_order: 'rgb'}
    LoadAnnotations: {with_bbox: True}
    PhotoMetricDistortion: {}
    Expand: {
      mean: [0, 0, 0],
      to_rgb: False,
      ratio_range: [1, 2]}
    MinIoURandomCrop: {
      min_ious: [0.1, 0.3, 0.5, 0.7, 0.9],
      min_crop_size: 0.3}
    JointResize: {
      img_scale: [[320, 320], [416, 416]],
      keep_ratio: True}
    JointRandomFlip: {flip_ratio: 0.5}
    Normalize: {
      mean: [0, 0, 0],
      std: [255, 255, 255],
      to_rgb: False}
    Pad: {size_divisor: 32}
    DefaultFormatBundle: {}
    Collect: {keys: ['img', 'gt_bboxes', 'gt_labels']}
  TEST_TRANSFORMS:
    LoadImageFromFile: {
      to_float32: True,
      backend: 'pillow',
      channel_order: 'rgb'}
    MultiScaleFlipAug: {
      img_scale: [416, 416],
      flip: False,
      transforms: {
        JointResize: {keep_ratio: False},
        Normalize: {
          mean: [0, 0, 0],
          std: [255, 255, 255],
          to_rgb: False},
        Pad: {size_divisor: 32},
        ImageToTensor: {keys: ['img']},
        Collect: {keys: ['img']}}}
  TRAIN_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: [["annotations/instances_train2017.json"]]
    DATA_PREFIX: ["train2017/"]
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: [["annotations/instances_val2017.json"]]
    DATA_PREFIX: ["val2017/"]
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: [["annotations/instances_val2017.json"]]
    DATA_PREFIX: ["val2017/"]
    TEST_MODE: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
