DATA:
  NAME: "DetRetailOneDataset"
  ROOT_PATH: "datasets/DetRetailDataset"
  TRAIN_TRANSFORMS:
    LoadImageFromFile: {to_float32: True}
    LoadAnnotations: {with_bbox: True}
    Rotate: {
      level: 5,
      img_fill_val: 114,
      prob: 0.5,
      max_rotate_angle: 30}
    Albu: {
      update_pad_shape: True,
      skip_img_without_anno: False,
      bbox_params: {
        type: 'BboxParams',
        format: 'pascal_voc',
        min_area: 4,
        min_visibility: 0.2,
        label_fields: ['gt_labels']},
      transforms: {
        PadIfNeeded: {
          min_height: 1280,
          min_width: 1024,
          border_mode: 0,
          value: [114, 114, 114],
          always_apply: True},
        RandomCrop: {
          width: 960,
          height: 720,
          always_apply: True},
        RandomScale: {
          scale_limit: 0.5,
          interpolation: 1,
          always_apply: True},
        CenterCrop: {
          width: 640,
          height: 480,
          always_apply: True},
        HorizontalFlip: {p: 0.5}}}
    HueSaturationValueJitter: {
      hue_ratio: 0.015,
      saturation_ratio: 0.7,
      value_ratio: 0.4}
    Normalize: {
      mean: [114, 114, 114],
      std: [255, 255, 255],
      to_rgb: True}
    DefaultFormatBundle: {}
    Collect: {keys: ['img', 'gt_bboxes', 'gt_labels']}
  TEST_TRANSFORMS:
    LoadImageFromFile: {}
    MultiScaleFlipAug: {
      img_scale: [640, 480],
      flip: False,
      transforms: {
        JointResize: {keep_ratio: False},
        Normalize: {
          mean: [114, 114, 114],
          std: [255, 255, 255],
          to_rgb: True},
        ImageToTensor: {keys: ['img']},
        Collect: {keys: ['img']}}}
  TRAIN_DATA:
    TYPE: "Balanced" # "Normal" "Concat" "Repeat" "Balanced"
    FLAG: 1
    DATA_INFO: ["train/a_annotations.json", "train/b_annotations.json"]
    DATA_PREFIX: ["train/a_images/", "train/a_annotations.json"]
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: ["train/a_annotations.json"]
    DATA_PREFIX: ["train/a_images/"]
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    TYPE: "Concat"
    FLAG: 1
    DATA_INFO: ["test/a_annotations.json"] 
    DATA_PREFIX: ["test/a_images"] 
    TEST_MODE: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
