DATA:
  NAME: "DetRetailDataset"
  ROOT_PATH: "datasets/DetRetailDataset"
  TRAIN_TRANSFORMS:
    MosaicPipeline: {
      individual_pipeline: {
        LoadImageFromFile: {backend: 'turbojpeg'},
        LoadAnnotations: {with_bbox: True},
        JointResize: {img_scale: [640, 640], keep_ratio: True}
      }, pad_val: 114}
    Albu: {
      update_pad_shape: True,
      skip_img_without_anno: False,
      bbox_params: {
        type: 'BboxParams',
        format: 'pascal_voc',
        min_area: 4,
        min_visibility: 0.2,
        label_fields: ['gt_labels'],
        check_each_transform: False},
      transforms: {
        PadIfNeeded: {
          min_height: 1920,
          min_width: 1920,
          border_mode: 0,
          value: [114, 114, 114],
          always_apply: True},
        RandomCrop: {
          width: 1280,
          height: 1280,
          always_apply: True},
        RandomScale: {
          scale_limit: 0.5,
          interpolation: 1,
          always_apply: True},
        CenterCrop: {
          width: 640,
          height: 640,
          always_apply: True},
        HorizontalFlip: {p: 0.5}}}
    HueSaturationValueJitter: {
      hue_ratio: 0.015,
      saturation_ratio: 0.7,
      value_ratio: 0.4}
    GtBBoxesFilter: {
      min_size: 2, 
      max_aspect_ratio: 20}
    Normalize: {
      mean: [114, 114, 114],
      std: [255, 255, 255],
      to_rgb: True}
    DefaultFormatBundle: {}
    Collect: {keys: ['img', 'gt_bboxes', 'gt_labels']}
  TEST_TRANSFORMS:
    LoadImageFromFile: {}
    MultiScaleFlipAug: {
      img_scale: [640, 640],
      flip: False,
      transforms: {
        JointResize: {keep_ratio: True},
        RandomFlip: {},
        Pad: {size_divisor: 32},
        Normalize: {
          mean: [114, 114, 114],
          std: [255, 255, 255],
          to_rgb: True},
        ImageToTensor: {keys: ['img']},
        Collect: {keys: ['img']}
        }
      }
  TRAIN_DATA:
    TYPE: "Balanced" # "Normal" "Concat" "Repeat" "Balanced"
    FLAG: 1
    DATA_INFO: ["train/a_annotations.json", "train/b_annotations.json"]
    DATA_PREFIX: ["train/a_images/", "train/b_images/"]
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: ["train/b_annotations.json"]
    DATA_PREFIX: ["train/b_images/"]
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    TYPE: "Concat"
    FLAG: 1
    DATA_INFO: ["test/a_annotations.json", "test/b_annotations.json"]
    DATA_PREFIX: ["test/a_images", "test/b_images"]
    TEST_MODE: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
