DATA:
  NAME: "MultiObjectDataset"
  ROOT_PATH: "/Users/qianzhiming/Desktop/data/objdet-datasets/MultiObjDet"
  TRAIN_TRANSFORMS:
    LoadImageFromFile: {
      to_float32: True,
      backend: 'pillow'}
    LoadAnnotations: {with_bbox: True}
    PhotoMetricDistortion: {}
    Expand: {
      mean: [0, 0, 0],
      to_rgb: True,
      ratio_range: [1, 2]}
    MinIoURandomCrop: {
      min_ious: [0.1, 0.3, 0.5, 0.7, 0.9],
      min_crop_size: 0.3}
    JointResize: {
      img_scale: [[320, 320], [416, 416]],
      keep_ratio: True}
    JointRandomFlip: {flip_ratio: 0.5}
    Normalize: {
      mean: [0, 0, 0],
      std: [255, 255, 255],
      to_rgb: True}
    Pad: {size_divisor: 32}
    DefaultFormatBundle: {}
    Collect: {keys: ['img', 'gt_bboxes', 'gt_labels']}
  TEST_TRANSFORMS:
    LoadImageFromFile: {}
    MultiScaleFlipAug: {
      img_scale: [416, 416],
      flip: False,
      transforms: {
        JointResize: {keep_ratio: False},
        Normalize: {
          mean: [0, 0, 0],
          std: [255, 255, 255],
          to_rgb: True},
        ImageToTensor: {keys: ['img']},
        Collect: {keys: ['img']}
        }
      }  
  TRAIN_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: ["metas/train.txt"] # [['tfrecords/train.tfrecord']] # 
    DATA_PREFIX: ["images/"]
    ANNO_PREFIX: ["annotations/"]
    IS_TFRECORD: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: ["metas/val.txt"] # [['tfrecords/val.tfrecord']] # 
    DATA_PREFIX: ["images/"]
    ANNO_PREFIX: ["annotations/"]
    IS_TFRECORD: False
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: ["metas/val.txt"] # [['tfrecords/val.tfrecord']] # 
    DATA_PREFIX: ["images/"]
    ANNO_PREFIX: ["annotations/"]
    IS_TFRECORD: False
    TEST_MODE: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
