DATA:
  NAME: "DetRetailOneDataset"
  ROOT_PATH: "datasets/DetRetailDataset"
  TRAIN_TRANSFORMS:
    LoadImageFromFile: {to_float32: True}
    LoadAnnotations: {with_bbox: True}
    PhotoMetricDistortion: {}
    JointResize: {
      img_scale: [960, 720],
      keep_ratio: False}
    Rotate: {
      level: 5,
      img_fill_val: 114,
      prob: 0.5,
      max_rotate_angle: 30}
    Normalize: {
      mean: [114, 114, 114],
      std: [255, 255, 255],
      to_rgb: True}
    Pad: {size_divisor: 32, pad_val: 114}
    DefaultFormatBundle: {}
    Collect: {keys: ['img', 'gt_bboxes', 'gt_labels']}
  TEST_TRANSFORMS:
    LoadImageFromFile: {}
    MultiScaleFlipAug: {
      img_scale: [960, 720],
      flip: False,
      transforms: {
        JointResize: {keep_ratio: False},
        Normalize: {
          mean: [114, 114, 114],
          std: [255, 255, 255],
          to_rgb: True},
        Pad: {size_divisor: 32, pad_val: 114},
        ImageToTensor: {keys: ['img']},
        Collect: {keys: ['img']}}}
  TRAIN_DATA:
    TYPE: "Balanced" # "Normal" "Concat" "Repeat" "Balanced"
    FLAG: 1
    DATA_INFO: ["train/a_annotations.json", "train/b_annotations.json"]
    DATA_PREFIX: ["train/a_images/", "train/a_annotations.json"]
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: ["train/a_annotations.json"]
    DATA_PREFIX: ["train/a_images/"]
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    TYPE: "Concat"
    FLAG: 1
    DATA_INFO: ["test/a_annotations.json"] 
    DATA_PREFIX: ["test/a_images"] 
    TEST_MODE: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
