DATA:
  NAME: "DetAnimalDataset"
  ROOT_PATH: "/Users/qianzhiming/Desktop/data/objdet-datasets/AnimalDet" # /root/datasets
  TRAIN_TRANSFORMS:
    LoadImageFromFile: {to_float32: True}
    LoadAnnotations: {with_bbox: True}
    PhotoMetricDistortion: {}
    Expand: {
      mean: [0, 0, 0],
      to_rgb: True,
      ratio_range: [1, 2]}
    MinIoURandomCrop: {
      min_ious: [0.1, 0.3, 0.5, 0.7, 0.9],
      min_crop_size: 0.3}
    JointResize: {
      img_scale: [[320, 320], [416, 416]],
      keep_ratio: True}
    JointRandomFlip: {flip_ratio: 0.5}
    Normalize: {
      mean: [0, 0, 0],
      std: [255, 255, 255],
      to_rgb: True}
    Pad: {size_divisor: 32}
    DefaultFormatBundle: {}
    Collect: {keys: ['img', 'gt_bboxes', 'gt_labels']}
  TEST_TRANSFORMS:
    LoadImageFromFile: {}
    MultiScaleFlipAug: {
      img_scale: [416, 416],
      flip: False,
      transforms: {
        JointResize: {keep_ratio: False},
        Normalize: {
          mean: [0, 0, 0],
          std: [255, 255, 255],
          to_rgb: True},
        Pad: {size_divisor: 32},
        ImageToTensor: {keys: ['img']},
        Collect: {keys: ['img']}}}
  TRAIN_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: [['tfrecords/train.tfrecord']] # ["metas/train.txt"]
    DATA_PREFIX: ["images/"]
    ANNO_PREFIX: ["annotations/"]
    IS_TFRECORD: True
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 0
  VAL_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: [['tfrecords/val.tfrecord']] # ["metas/val.txt"]
    DATA_PREFIX: ["images/"]
    ANNO_PREFIX: ["annotations/"]
    IS_TFRECORD: True
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 0
  TEST_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: [['tfrecords/val.tfrecord']] # ["metas/val.txt"]
    DATA_PREFIX: ["images/"]
    ANNO_PREFIX: ["annotations/"]
    IS_TFRECORD: True
    TEST_MODE: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 0
