DATA:
  NAME: "CocoDataset"
  ROOT_PATH: "datasets/CocoDataset"
  TRAIN_TRANSFORMS:
    LoadImageFromFile: {
      to_float32: True,
      backend: 'pillow'}
    LoadAnnotations: {with_bbox: True}
    PhotoMetricDistortion: {}
    JointResize: {
      img_scale: [320, 320],
      ratio_range: [0.1, 2.0],
      keep_ratio: True}
    JointRandomCrop: {crop_size: [224, 224]}
    JointRandomFlip: {flip_ratio: 0.5}
    Normalize: {
      mean: [123.675, 116.28, 103.53],
      std: [58.395, 57.12, 57.375],
      to_rgb: True}
    Pad: {size: [224, 224]}
    DefaultFormatBundle: {}
    Collect: {keys: ['img', 'gt_bboxes', 'gt_labels']}
  TEST_TRANSFORMS:
    LoadImageFromFile: {}
    MultiScaleFlipAug: {
      img_scale: [224, 224],
      flip: False,
      transforms: {
        JointResize: {keep_ratio: True},
        JointRandomFlip: {},
        Normalize: {
          mean: [123.675, 116.28, 103.53],
          std: [58.395, 57.12, 57.375],
          to_rgb: True},
        Pad: {size: [224, 224]},
        ImageToTensor: {keys: ['img']},
        Collect: {keys: ['img']}
        }
      }  
  TRAIN_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: ["metas/train.txt"]
    DATA_PREFIX: ["images/"]
    ANNO_PREFIX: ["annotations/"]
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: ["metas/val.txt"]
    DATA_PREFIX: ["images/"]
    ANNO_PREFIX: ["annotations/"]
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: ["metas/val.txt"]
    DATA_PREFIX: ["images/"]
    ANNO_PREFIX: ["annotations/"]
    TEST_MODE: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
