DATA:
  NAME: "EmbLocRetailDataset"
  ROOT_PATH: "datasets/DetRetailDataset"
  TRAIN_TRANSFORMS:
    ImgResize: {size: 128}
    PhotoMetricDistortion: {
      brightness_delta: 32,
      contrast_range: [0.5, 1.5],
      saturation_range: [0.5, 1.5],
      hue_delta: 18}
    Normalize: {
      mean: [125.307, 122.961, 113.8575], 
      std: [51.5865, 50.847, 51.255], 
      to_rgb: True
      }
    DefaultFormatBundle: {}
    EmbCollect: {
      keys: ['img', 'label', 'bbox', 'bbox_id']
      }
  TEST_TRANSFORMS:
    ImgResize: {size: 128}
    Normalize: {
      mean: [125.307, 122.961, 113.8575], 
      std: [51.5865, 50.847, 51.255], 
      to_rgb: True
      }
    DefaultFormatBundle: {}
    EmbCollect: {
      keys: ['img', 'label', 'bbox', 'bbox_id']
      }
  TRAIN_DATA:
    TYPE: "Balanced" # "Normal" "Concat" "Repeat" "Balanced"
    FLAG: 1
    DATA_INFO: ["train/a_annotations.json", "train/b_annotations.json", "test/b_annotations.json"]
    DATA_PREFIX: ["train/a_images/", "train/b_images/", "test/b_images/"]
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    TYPE: "Concat"
    FLAG: 1
    DATA_INFO: ["train/a_annotations.json"]
    DATA_PREFIX: ["train/a_images/"]
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    TYPE: "Concat"
    FLAG: 1
    DATA_INFO: ["test/a_annotations.json"] 
    DATA_PREFIX: ["test/a_images/"] 
    TEST_MODE: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
