MODEL:
  BASE: "models/detections/det_faster_rcnn_r50_fpn.yaml"
  PRETRAINED_MODEL_PATH: ""
  ROI_HEAD:
    bbox_head:
      num_classes: 20
DATA:
  BASE: "datasets/detections/det_voc.yaml"
  # ROOT_PATH: "datasets/VOCDataset"
  ROOT_PATH: "/home/qzm/Work/Data/VOC/VOCdevkit"
  TRAIN_DATA:
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
SCHEDULE:
  BASE: "schedulers/schedule_2x.yaml"
  OPTIMIZER: 
    lr: 0.002
RUNTIME:
  BASE: "runtimes/local_runtime.yaml"
