MODEL:
  BASE: "models/detection2ds/det_faster_rcnn_r50_fpn.yaml"
  PRETRAINED_MODEL_PATH: ""
  ROI_HEAD:
    bbox_head:
      num_classes: 20
DATA:
  BASE: "datasets/detection2ds/det_voc.yaml"
  TRAIN_DATA:
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
SCHEDULE:
  BASE: "schedulers/schedule_2x.yaml"
  OPTIMIZER: 
    lr: 0.002
RUNTIME:
  BASE: "runtimes/runtime_local.yaml"
