MODEL:
  TYPE: "emb"
  NAME: "ImgClsLocEmbedder"
  PRETRAINED_MODEL_PATH: "meta/models/resnet50-19c8e357.pth"
  BACKBONE:
    type: "ResNet"
    depth: 50
    num_stages: 4
    out_indices: [3]
    norm_cfg: {
      type: 'BN', 
      requires_grad: True}
    norm_eval: True
  NECK:
    type: "GlobalAveragePooling"
  EMB_HEAD:
    type: "MlpLocEmbHead"
    in_channels: 2048
    out_channels: 512
    loss:
      type: 'TripletMarginLoss'
