MODEL:
  TYPE: "det"
  NAME: "YOLOV4"
  PRETRAINED_MODEL_PATH: ""
  BACKBONE:
    type: "CSPDarknet53"
  NECK:
    type: "YoloV4DarkNeck"
  BBOX_HEAD:
    type: 'YOLOV3Head'
    num_classes: 80
    in_channels: [512, 256, 128]
    out_channels: [1024, 512, 256]
    anchor_generator: {
      type: 'YOLOAnchorGenerator',
      base_sizes: [[[142, 110], [192, 243], [459, 401]],
                    [[36, 75], [76, 55], [72, 146]],
                    [[12, 16], [19, 36], [40, 28]]],
      strides: [32, 16, 8]}
    bbox_coder: {
      type: 'YOLOBBoxCoder', 
      scale_x_y: 1.05}
    featmap_strides: [32, 16, 8]
    loss_cls: {
      type: 'CrossEntropyLoss',
      use_sigmoid: True,
      loss_weight: 1.0,
      reduction: 'sum'} # sum
    loss_conf: {
      type: 'CrossEntropyLoss',
      use_sigmoid: True,
      loss_weight: 1.0,
      reduction: 'sum'}
    loss_xy: {
      type: 'CrossEntropyLoss',
      use_sigmoid: True,
      loss_weight: 2.0,
      reduction: 'sum'}
    loss_wh: {
      type: 'MSELoss', 
      loss_weight: 2.0, 
      reduction: 'sum'}
  TRAIN_CFG:
    assigner: {
      type: 'GridAssigner', 
      pos_iou_thr: 0.5, 
      neg_iou_thr: 0.5, 
      min_pos_iou: 0}
  TEST_CFG:
    nms_pre: 1000
    min_bbox_size: 0
    score_thr: 0.05
    conf_thr: 0.005
    nms: {
      type: 'common_nms', 
      iou_threshold: 0.45}
    max_per_img: 100
