SCHEDULE:
  TOTAL_EPOCHS: 100
  OPTIMIZER:
    type: "SGD"
    lr: 0.08
    momentum: 0.9
    weight_decay: 0.00004
    PARAMWISE_CFG:
      custom_keys: {
        'backbone': { lr_mult: 0.1, decay_mult: 1 },
      }
  OPTIMIZER_CONFIG:
    grad_clip: {
      max_norm: 35,
      norm_type: 2}
    fp16: False
  LR_POLICY:
    policy: "CosineAnnealing"
    min_lr_ratio: 0.001
    warmup: "linear"
    warmup_iters: 1000
    warmup_ratio: 0.008
