SCHEDULE:
  TOTAL_EPOCHS: 300
  OPTIMIZER:
    type: "SGD"
    lr: 0.01
    momentum: 0.937
    weight_decay: 0.0005
    nesterov: True
    PARAMWISE_CFG: {
      bias_decay_mult: 0., 
      norm_decay_mult: 0.}
  OPTIMIZER_CONFIG:
    grad_clip: {
      max_norm: 35,
      norm_type: 2}
    fp16: False
  LR_POLICY:
    policy: "CosineAnnealing"
    min_lr_ratio: 0.01
