Data:
  NAME: 'KittiDataset'
  ROOT_PATH: 'data/other-datasets/Kitti/Object3D'
  TRAIN_TRANSFORMS:
    PointCloudAlbu: {
      max_points_per_voxel: 100,
      max_voxels: 20000,
      create_gt: True,
      shuffle_points: True,
      gt_rotation_noise: [-0.78539816, 0.78539816],
      gt_loc_noise_std: [0.5, 0.5, 0.5],
      global_rotation_noise: [-0.78539816, 0.78539816],
      global_scaling_noise: [0.95, 1.05],
      min_points_in_gt: 10,
      random_flip_x: True,
      random_flip_y: True
    }
    D3DDefaultFormatBundle: {}
    D3DCollect: {keys: [
      "voxels",
      "num_points",
      "coordinates",
      "num_voxels",
      "metrics",
      "anchors",
      "labels",
      "reg_targets"
    ]}
  TEST_TRANSFORMS:
    PointCloudAlbu: {
      max_points_per_voxel: 100,
      max_voxels: 20000,
      create_gt: True,
      shuffle_points: False,
      gt_rotation_noise: [0, 0],
      gt_loc_noise_std: [0, 0, 0],
      global_rotation_noise: [0, 0],
      global_scaling_noise: [1, 1],
      min_points_in_gt: 10,
      random_flip_x: False,
      random_flip_y: False
    }
    D3DDefaultFormatBundle: {}
    D3DCollect: {keys: [
      "voxels",
      "num_points",
      "coordinates",
      "num_voxels",
      "metrics",
      "anchors"
    ]}
  TRAIN_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: [["kitti_infos_train.pkl"]]
    DATA_PREFIX: ["train/"]
    RPN_STRIDES: 2
    VOXEL_SIZE: [0.2, 0.2, 4]
    POINT_CLOUD_RANGE: [0., -40., -3.0, 70.4, 40., 1.0]
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: [["kitti_infos_val.pkl"]]
    DATA_PREFIX: ["val/"]
    RPN_STRIDES: 2
    VOXEL_SIZE: [0.2, 0.2, 4]
    POINT_CLOUD_RANGE: [0., -40., -3.0, 70.4, 40., 1.0]
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: [["kitti_infos_test.pkl"]]
    DATA_PREFIX: ["test/"]
    RPN_STRIDES: 2
    VOXEL_SIZE: [0.2, 0.2, 4]
    POINT_CLOUD_RANGE: [0., -40., -3.0, 70.4, 40., 1.0]
    TEST_MODE: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
