MODEL:
  TYPE: "det"
  NAME: "YOLOV5"
  PRETRAINED_MODEL_PATH: ""
  BACKBONE:
    type: "YOLOV5Net"
    depth_multiple: 0.33  # {s:0.33, m: 0.67, l: 1.0, x: 1.33}
    width_multiple: 0.5  # {s:0.5, m: 0.75, l: 1.0, x: 1.25}  
  BBOX_HEAD:
    type: 'YOLOV5Head'
    num_classes: 80
    in_channels: [512, 256, 128]
    dw_ratios: [0.33, 0.5]
    anchor_generator: {
      type: 'YOLOAnchorGenerator',
      base_sizes: [[[116, 90], [156, 198], [373, 326]],
                   [[30, 61], [62, 45], [59, 119]],
                   [[10, 13], [16, 30], [33, 23]]],
      strides: [32, 16, 8]}
    bbox_coder: {type: 'YOLOV5BBoxCoder'}
    featmap_strides: [32, 16, 8]
    loss_cls: {
      type: 'CrossEntropyLoss',
      use_sigmoid: True,
      loss_weight: 1.0,
      reduction: 'sum'} # sum
    loss_conf: {
      type: 'CrossEntropyLoss',
      use_sigmoid: True,
      loss_weight: 1.0,
      reduction: 'sum'}
    loss_xy: {
      type: 'CrossEntropyLoss',
      use_sigmoid: True,
      loss_weight: 2.0,
      reduction: 'sum'}
    loss_wh: {
      type: 'MSELoss', 
      loss_weight: 2.0, 
      reduction: 'sum'}
  TRAIN_CFG:
    assigner: {
      type: 'GridAssigner', 
      pos_iou_thr: 0.5, 
      neg_iou_thr: 0.5, 
      min_pos_iou: 0}
  TEST_CFG:
    nms_pre: 1000
    min_bbox_size: 0
    score_thr: 0.0000001
    conf_thr: 0.001
    nms: {
      type: 'common_nms', 
      iou_threshold: 0.6}
    max_per_img: 100
