MODEL:
  TYPE: "det"
  NAME: "YOLOV5"
  PRETRAINED_MODEL_PATH: ""
  BACKBONE:
    type: 'DarknetCSP'
    scale: 'v5x5p'
    out_indices: [2, 3, 4]
  NECK:
    type: 'YOLOV5Neck'
    in_channels: [320, 640, 1280]
    out_channels: [320, 640, 1280]
  BBOX_HEAD:
    type: 'YOLOCSPHead'
    num_classes: 80
    in_channels: [320, 640, 1280]
    anchor_generator: {
      type: 'YOLOV4AnchorGenerator',
      base_sizes: [[[12, 16], [19, 36], [40, 28]],
                   [[36, 75], [76, 55], [72, 146]],
                   [[142, 110], [192, 243], [459, 401]]],
      strides: [8, 16, 32]}
    bbox_coder: {type: 'YOLOV4BBoxCoder'}
    featmap_strides: [8, 16, 32]
    loss_cls: {
      type: 'CrossEntropyLoss',
      use_sigmoid: True,
      loss_weight: 32.0}
    loss_conf: {
      type: 'CrossEntropyLoss',
      use_sigmoid: True,
      loss_weight: 64.0}
    loss_bbox: {
      type: 'CIoULoss', 
      loss_weight: 3.2}
  TEST_CFG:
    nms_pre: -1
    min_bbox_size: 0
    score_thr: 0.001
    conf_thr: 0.005
    nms: {
      type: 'common_nms', 
      iou_threshold: 0.65}
    max_per_img: 300
