MODEL:
  TYPE: "det"
  NAME: "YOLOV4"
  PRETRAINED_MODEL_PATH: ""
  BACKBONE:
    type: 'DarknetCSP'
    scale: 'v4x5p'
    out_indices: [3, 4, 5]
  NECK:
    type: 'YOLOV4Neck'
    in_channels: [320, 640, 640]
    out_channels: [320, 640, 1280]
    csp_repetition: 3
  BBOX_HEAD:
    type: 'YOLOCSPHead'
    num_classes: 80
    in_channels: [320, 640, 1280]
    anchor_generator: {
      type: 'YOLOV4AnchorGenerator',
      base_sizes: [[[142, 110], [192, 243], [459, 401]],
                    [[36, 75], [76, 55], [72, 146]],
                    [[12, 16], [19, 36], [40, 28]]],
      strides: [8, 16, 32]}
    bbox_coder: {type: 'YOLOV4BBoxCoder'}
    featmap_strides: [8, 16, 32]
    loss_cls: {
      type: 'CrossEntropyLoss',
      use_sigmoid: True,
      loss_weight: 32.0}
    loss_conf: {
      type: 'CrossEntropyLoss',
      use_sigmoid: True,
      loss_weight: 64.0}
    loss_bbox: {
      type: 'GIoULoss',
      loss_weight: 3.2}
  TEST_CFG:
    nms_pre: -1
    min_bbox_size: 0
    score_thr: 0.001
    conf_thr: 0.005
    nms: {
      type: 'common_nms', 
      iou_threshold: 0.5}
    max_per_img: 300
