SCHEDULE:
  TOTAL_EPOCHS: 24
  OPTIMIZER:
    type: "SGD"
    lr: 0.02
    momentum: 0.9
    weight_decay: 0.0001
  LR_POLICY:
    policy: "step"
    warmup: "linear"
    warmup_iters: 500
    warmup_ratio: 0.001
    step: [16, 22]
