SCHEDULE:
  TOTAL_EPOCHS: 100
  OPTIMIZER:
    type: "SGD"
    lr: 0.08
    momentum: 0.9
    weight_decay: 0.00004
  OPTIMIZER_CONFIG:
    grad_clip: {
      max_norm: 10,
      norm_type: 2}
  LR_POLICY:
    policy: "CosineAnnealing"
    min_lr_ratio: 0.001
    warmup: "linear"
    warmup_iters: 2000
    warmup_ratio: 0.008
