SCHEDULE:
  TOTAL_EPOCHS: 100
  OPTIMIZER:
    type: "SGD"
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005
  OPTIMIZER_CONFIG:
    grad_clip: {
      max_norm: 35,
      norm_type: 2}
  LR_POLICY:
    policy: "step"
    warmup: "linear"
    warmup_iters: 5000
    warmup_ratio: 0.01
    step: [66, 92]
